# Generated by Django 5.1.3 on 2024-11-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Userid', models.IntegerField()),
                ('Password', models.IntegerField()),
            ],
            options={
                'db_table': 'register_table',
            },
        ),
    ]
