# Generated by Django 5.1.3 on 2024-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
