# Generated by Django 5.1.3 on 2024-12-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_name_register_name_remove_register_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
